
### Realizar Notificação

POST /api/v1/evidence HTTP/1.1
Host: localhost:8083
Content-Type: multipart/form-data; boundary=arquivo

--arquivo
Content-Disposition: form-data; name=evidence; filename=testee.jpg;
Content-Type: image/jpg

< ./evidence-api/teste.jpg
--arquivo--